config/routes.rb
Rails.application.routes.draw do
  resources :testruns do
    resources :apps, :controller =>'testrun_apps' do
      collection do

      end

      end
  end

  resources :querys do
    collection do
      post :search
      post :downloadcsv
    end
  end

end

app/models/query.rb
class Query < App
  belongs_to :app



  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |app|
        csv << app.attributes.values_at(*column_names)
      end
    end
  end




end

app/controllers/querys_controller.rb
class QuerysController < ApplicationController

  require 'csv'
  def index
    @apps = App.all
    @pkg = [] << ''
    @pkg += App.uniq.pluck(:AppPackageName)

    @class = [] << ''
    @class +=App.uniq.pluck(:AppClass)


    @result = [] << ''
    @result += App.uniq.pluck(:ApkResult)

    @manual_result = [] << ''
    @manual_result  += App.uniq.pluck(:TesterResult)
  end


  def search

    @pkg = [] << ''
    @pkg += App.uniq.pluck(:AppPackageName)
    @class = [] << ''
    @class +=App.uniq.pluck(:AppClass)


    @result = [] << ''
    @result += App.uniq.pluck(:ApkResult)

    @manual_result = [] << ''
    @manual_result  += App.uniq.pluck(:TesterResult)

    sql="SELECT * FROM apps WHERE "

    sql_array =[]
    sql_array.push(sql)
      if !params[:AppPackageName].blank?
        sql_param = "AppPackageName = ? and "
        sql_array[0] +=sql_param
        sql_array.push(params[:AppPackageName])
      end
      if !params[:AppClass].blank?
        sql_param = "AppClass = ? and "
        sql_array[0] +=sql_param
        sql_array.push(params[:AppClass])
      end
      if !params[:ApkResult].empty?
        sql_param = "ApkResult = ? and "
        sql_array[0] +=sql_param
        sql_array.push(params[:ApkResult])
      end
      if !params[:TesterResult].empty?
        sql_param = "TesterResult = ? "
        sql_array[0] +=sql_param
        sql_array.push(params[:TesterResult])
      end

      @ral = sql_array[0].end_with? "and "
      sql_array[0]= ( sql_array[0])[0..-5] if(@ral)


      @sql_array = sql_array
      @apps = App.find_by_sql(sql_array)
  end

  def downloadcsv
     @apps = params[:apps]
     @sql_array = params[:sql_array]


     @query_apps = App.find_by_sql(@sql_array)

     #@query_apps = App.where(:ApkResult => 'Pass' , :TesterResult => 'Fail')

        respond_to do |format|
          format.html {}
          format.csv { render text: @query_apps.to_csv }
          format.xls { send_data @query_apps.to_csv(col_sep: "\t") }

        end





  end

  def show

  end

  def create

  end

  def edit

  end

  def destroy

  end


  def hello
    @print_hello =  params[:hello]
  end
end

app/helpers/querys_helper.rb
module QuerysHelper
end

app/views/querys/_apps.html.erb
<td><%= app.AppNumber %> <%= link_to image_tag("gp4.png"  , :width => 20 , :height => 20) , app.AppLink %></td>
<td>
  <span class="label label-warning"><%= app.AppClass %></span>
  <span class="label label-info"> <%= app.AppCategory%></span>
</td>

<td>
  <div><%= app.AppName %></div>
  <div class="label label-success"><%= app.AppPackageName %></div>
</td>


<td><%= app.AppVersion %></td>
<td><%= app.AppNativeCode %></td>
<td><%= app.ApkResult %></td>
<td><%= app.AppInstallResult%></td>
<td><%= app.AppLaunchResult %></td>
<td><%= app.AppMonkeyResult %></td>
<td><%= app.Tester %></td>
<td><%= app.TesterResult %></td>
<td></td>
<td></td>

app/views/querys/_filter.html.erb
<thread>
  <tr >
    <th>

    </th>
    <th>

      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          篩選 <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Application', testrun_apps_path(:AppClass => :Application,:apps => @apps ) %></li>
          <li><%= link_to 'Game'       , testrun_apps_path(:AppClass => :Game,:apps => @apps) %></li>


        </ul>


      </div>

    </th>
    <th></th>


    <th></th>
    <th>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          篩選 <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'armeabi-v7a', testrun_apps_path(:AppNativeCode => 'armeabi-v7a',:apps => @apps , :testrun => @testrun) %></li>
          <li><%= link_to 'armeabi', testrun_apps_path(:AppNativeCode => 'armeabi',:apps => @apps , :testrun => @testrun) %></li>
          <li><%= link_to 'x86', testrun_apps_path(:AppNativeCode => 'x86',:apps => @apps , :testrun => @testrun) %></li>


        </ul>
      </div>
    </th>
    <th>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          篩選 <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'All', testrun_apps_path(:ApkResult => :All,:apps => @apps , :testrun => @testrun) %></li>
          <li><%= link_to 'Pass', testrun_apps_path(:ApkResult => :Pass,:apps => @apps , :testrun => @testrun) %></li>
          <li><%= link_to 'Fail', testrun_apps_path(:ApkResult => :Fail,:apps => @apps , :testrun => @testrun) %></li>

        </ul>
      </div>
    </th>
    <th>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          篩選 <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Pass', testrun_apps_path(:AppInstallResult => :Pass,:apps => @apps) %></li>
          <li><%= link_to 'Fail', testrun_apps_path(:AppInstallResult => :Fail,:apps => @apps) %></li>

        </ul>
      </div>
    </th>

    <th>


    </th>


    <th>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          篩選 <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Pass', testrun_apps_path(:AppLaunchResult => :Pass,:apps => @apps) %></li>
          <li><%= link_to 'Fail', testrun_apps_path(:AppLaunchResult => :Fail,:apps => @apps) %></li>

        </ul>
      </div>
    </th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thread>

app/views/querys/downloadCSV.html.erb
<%= debug(@apps) %>
<%= debug(@sql_array) %>
<%= debug(@query_apps) %>

app/views/querys/index.html.erb
<h1>Products</h1>

<p>
  Download:


</p>

<%= render :partial => 'apps_summary'  ,:locals => { :apps => @apps} %>


<div class="box-content">



  <div class="row form-group">
    <div class="col-sm-2">包裝名稱</div>
    <div class="col-sm-2">APK類別</div>
    <div class="col-sm-2">測試結果</div>
    <div class="col-sm-2">複測結果</div>
    <div class="col-sm-2"></div>

  </div>
  <div class="row form-group">

    <%= form_tag search_querys_path, :method => :post,:multipart => true do %>
      <div class="col-sm-2">
        <%= select_tag "AppPackageName", options_for_select(@pkg,'') , { :class => 'form-control'}%>
      </div>
      <div class="col-sm-2">
        <%= select_tag "AppClass", options_for_select(@class,'',) ,{ :class => 'form-control'}%>
      </div>
      <div class="col-sm-2">
        <%= select_tag "ApkResult", options_for_select(@result,''), { :class => 'form-control'}%>
      </div>
      <div class="col-sm-2">
        <%= select_tag "TesterResult", options_for_select(@manual_result,''), { :class => 'form-control'}%>
      </div>
        <%= submit_tag 'Query', {:class => 'btn btn-primary'} %>




    <% end %>


  </div>
</div>

<div>
  <table class="table table-striped">
    <!-- Title -->
    <%= render :partial =>'form' %>

    <tbody>
    <% @apps.each do |app| %>
    <tr>
        <%= render :partial =>'apps', :locals => {:app=> app} %>

    </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/querys/search.html.erb
<h1>Products</h1>

<p>
  Download:

<div class="btn-group col-md-1 col-md-offset-5" role="group" aria-label="...">

  <td><%= button_to 'download', downloadcsv_querys_path(:apps => @apps)  %></td>




</div>

</p>

<%= render :partial => 'apps_summary'  ,:locals => { :apps => @apps} %>


<div class="box-content">
  <div class="row form-group">
    <div class="col-sm-2">包裝名稱</div>
    <div class="col-sm-2">APK類別</div>
    <div class="col-sm-2">測試結果</div>
    <div class="col-sm-2">複測結果</div>
    <div class="col-sm-2"></div>

  </div>
  <div class="row form-group">

    <%= form_tag search_querys_path, :method => :post,:multipart => true do %>
        <div class="col-sm-2">
          <%= select_tag "AppPackageName", options_for_select(@pkg,'') , { :class => 'form-control'}%>
        </div>
        <div class="col-sm-2">
          <%= select_tag "AppClass", options_for_select(@class,'',) ,{ :class => 'form-control'}%>
        </div>
        <div class="col-sm-2">
          <%= select_tag "ApkResult", options_for_select(@result,''), { :class => 'form-control'}%>
        </div>
        <div class="col-sm-2">
          <%= select_tag "TesterResult", options_for_select(@manual_result,''), { :class => 'form-control'}%>
        </div>
        <%= submit_tag 'Query', {:class => 'btn btn-primary'} %>

    <% end %>


  </div>
</div>

<div>
  <table class="table table-striped">
    <!-- Title -->
    <%= render :partial =>'form' %>

    <tbody>
    <% @apps.each do |app| %>
        <tr>
          <%= render :partial =>'apps', :locals => {:app=> app} %>

        </tr>
    <% end %>
    </tbody>
  </table>
</div>