config/routes.rb
Rails.application.routes.draw do
  resources :testruns do
    resources :apps, :controller =>'testrun_apps' do
      collection do

      end

      end
  end

  resources :querys do
    collection do
      post :search
      post :downloadcsv
    end
  end

end

app/controllers/testrun_apps_controller.rb
class TestrunAppsController < ApplicationController
	skip_before_action :verify_authenticity_token

    def index
      sort_by =(params[:order] == 'AppNumber')? 'AppNumber' : 'created_at'
      @testrun = Testrun.find( params[:testrun_id])
      if params[:AppClass]
        @apps = @testrun.apps.where(:AppClass => params[:AppClass])
        .order(sort_by).page(params[:page]).per(100)
      elsif params[:AppNativeCode]
        @apps = @testrun.apps.where("AppNativeCode LIKE ? "    , "#{params[:AppNativeCode]}%")
        .order(sort_by).page(params[:page]).per(100)
      elsif  params[:ApkResult] && params[:ApkResult] != "All"
        @apps = @testrun.apps.where(:ApkResult => params[:ApkResult])
        .order(sort_by).page(params[:page]).per(100)
      elsif params[:AppInstallResult]
        @apps = @testrun.apps.where(:AppInstallResult => params[:AppInstallResult])
        .order(sort_by).page(params[:page]).per(100)
      elsif params[:AppLaunchResult]
        @apps = @testrun.apps.where(:AppLaunchResult  => params[:AppLaunchResult])
        .order(sort_by).page(params[:page]).per(100)
      else

        @apps = @testrun.apps.order(sort_by).page(params[:page]).per(100)
      end

      respond_to do |format|
        format.html {}
        format.csv { render text: @apps.to_csv }
        format.json { render :json => @apps.to_json }
        format.xml { render :xml => @apps.to_xml }
        format.xls
        end

    end



    def show
      @testrun = Testrun.find(params[:testrun_id])
    	@app =@testrun.apps.find(params[:id])


      respond_to do |format|
        format.html {}
        format.json { render :json => @app.to_json }
        format.xml { render :xml => @app.to_xml }

      end
    end

    def edit
      @testrun = Testrun.find(params[:testrun_id])
      @app = @testrun.apps.find(params[:id])
    end




    def new
    	@app = @testrun.apps.build
    end


    def create
      @testrun = Testrun.find(params[:testrun_id])
    	@app = @testrun.apps.build(app_params)
    	if @app.save
    		redirect_to testrun_apps_url (@testrun)
    	else
    			render :action => :new
    	end
    end


    def update
      @testrun = Testrun.find(params[:testrun_id])
      @app = @testrun.apps.find(params[:id])
    	if @app.update(:Tester => params.require(:app)[:Tester],
                     :TesterResult => params.require(:app)[:TesterResult],
                     :TesterComment => params.require(:app)[:TesterComment],
                     :TTBugID => params.require(:app)[:TTBugID],
                     :BugZillaBugID => params.require(:app)[:BugZillaBugID])
    		redirect_to testrun_apps_url (@testrun)
    	else
    		render :action => :edit
    	end
    end

    def destroy
      @testrun = Testrun.find( params[:testrun_id])
    	@app = @testrun.apps.find(params[:id])
    	@app.destroy
    	redirect_to testrun_apps_url(@testrun)
    end

  protected
  	def find_testrun
  		@testrun = Testrun.find( params[:testrun_id])
  	end

  	def app_params
  		params.require(:app).permit(:AppPackageName)
    end

    

end

app/helpers/testrun_apps_helper.rb
module TestrunAppsHelper
end

app/views/testrun_apps/_apps.html.erb
<td><%= app.AppNumber %> <%= link_to image_tag("gp4.png"  , :width => 20 , :height => 20) , app.AppLink %></td>
<td>
  <span class="label label-warning"><%= app.AppClass %></span>
  <span class="label label-info"> <%= app.AppCategory%></span>
</td>
<td>

  <!--<div class="label label-success"><%= app.AppPackageName %></div>-->
  <kbd> <%= app.AppPackageName %></kbd>
  <div><%= app.AppName %></div>
</td>
<td>
  <kbd>  <%= app.AppVersion %></kbd>

</td>
<td><%= app.AppNativeCode %></td>
<td><%= app.ApkResult %></td>
<td><%= app.AppInstallResult%></td>
<td><%= app.AppLaunchResult %></td>
<td><%= app.AppMonkeyResult %></td>
<td><%= app.Tester %></td>
<td><%= app.TesterResult %></td>

app/views/testrun_apps/_form.html.erb
<thread>
  <tr>
    <th>#</th>
    <th>類別/分類</th>
    <th>名稱</th>
    <th>版本</th>
    <th>NDK</th>
    <th>總結果</th>
    <th>安裝測試</th>
    <th>啟動測試</th>
    <th>猴子測試</th>
    <th>覆測人</th>
    <th>覆測結果</th>

    <th>動作</th>
  </tr>
</thread>

app/views/testrun_apps/_summary.html.erb
    <div class="row">

        <div class="row">
          <div class="col-xs-4">總測試數<b><%= @testrun.TestRun_TotalAppsCount%></b></div>

          <div class="col-xs-4">總失敗數<b><%= @testrun.TestRun_TotalFailCount%></b></div>

          <div class="col-xs-4">成功率<b><%=  @testrun.TestRun_PassRate%></b></div>
        </div>
        <div class="row">
          <div class="col-xs-4">總安裝失敗數<b><%= @testrun.TestRun_InstallFailCount %></b></div>
          <div class="col-xs-4">總啟動失敗數<b><%= @testrun.TestRun_LaunchRunningFail %></b></div>
          <div class="col-xs-4">總猴子失敗數<b><%= @testrun.TestRun_MonkeyRunningFail %></b></div>
        </div>




    </div>

app/views/testrun_apps/downloadcsv.xls.erb
<table border="1">
  <tr>

    <th>Name</th>
    <th>Result</th>

  </tr>
  <% @apps.each do |app| %>
      <tr>

        <td><%= app.AppName %></td>
        <td><%= app.ApkResult %></td>

      </tr>
  <% end %>
</table>

app/views/testrun_apps/edit.html.erb
<%= link_to 'back index', testrun_apps_path %>
<div class="col-md-12">
  <table class="table table-striped">
    <%= render :partial => 'form'%>


    <tbody>
    <tr>
      <%= render :partial => 'apps' , :locals => { :app => @app } %>
    </tr>
    </tbody>
  </table>
</div>

<%= simple_form_for @app,
                    :url=> url_for( :action => 'update' , :controller =>  'testrun_apps'),
                    :method=> 'patch' do |f| %>

    <table>
      <tr>
        <th colspan="4"><h2>覆測表單填寫</h2></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td> <%= f.input :TTBugID  , :label => "TT Bug ID" ,:input_html=>{:style=> 'width: 120px'}  %></td>
        <td><%= f.input :BugZillaBugID  , :label => "BugZilla Bug ID" ,:input_html=>{:style=> 'width: 120px'}  %></td>


        <td></td>
        <td></td>

      </tr>
      <tr>
        <td><%= f.input :Tester  , :label => "複測人" ,:input_html=>{:style=> 'width: 120px'}  %></td>
        <td><%= f.input :TesterResult  , :label => "複測結果" ,:input_html=>{:style=> 'width: 120px'}  %></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td colspan="4"><%= f.input :TesterComment  ,as: :text , :label => "複測評論" ,:input_html => { :rows => 4 , :style => 'width:400px'}%></td>

      </tr>
       </table>
    <%= f.button :submit %>
<% end %>

app/views/testrun_apps/index.html.erb
<div class="page-header">

  <div class="row">
    <div class="col-md-10">
      <h2>TestRun Result <span style="font-size: 16pt" class="badge"><%= @apps.length %></span> </h2>
    </div>
    <div class="col-md-2">
      <h2><%= button_to "Download csv", testrun_apps_path(format: "csv")   ,:class => "btn btn-warning",:method => :get%></h2>
    </div>
  </div>
</div>

<h4 class="page-header">Σ SUMMARY</h4>
<nav class="navbar navbar-default">
  <div class="container-fluid">

      <%= render :partial => 'summary' %>

  </div>
</nav>

<div>

	<table class="table table-striped">

      <!-- Title -->
      <%= render :partial => 'form' %>

      <tbody>
        <% @apps.each do |app| %>
        <tr>
          <%= render :partial => 'apps'  ,:locals => { :app => app} %>


          <td>

            <!-- Split button -->
            <div class="btn-group">
              <button type="button" class="btn btn-danger">Action</button>
              <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Detail', testrun_app_path( @testrun , app),:method => :get%></li>

                <li class="divider"></li>
                <li><%= link_to 'Edit', edit_testrun_app_path( @testrun , app),:method => :get%></li>
                <li class="divider"></li>
                <li> <%= link_to 'Delete', testrun_app_path( @testrun , app),:method => :delete%></li>


              </ul>
            </div>
          </td>

        </tr>
        <% end %>
      </tbody>
    </table>

</div>
<%= paginate @apps %>

<div class="col-md-12">
  <%= link_to 'back index', testruns_path %>
</div>

app/views/testrun_apps/index.xls.erb
<table border="1">
  <tr>

    <th>Name</th>
    <th>Result</th>

  </tr>
  <% @apps.each do |app| %>
      <tr>

        <td><%= app.AppName %></td>
        <td><%= app.ApkResult %></td>

      </tr>
  <% end %>
</table>

app/views/testrun_apps/search.html.erb
<%= render :partial => 'apps_summary'  ,:locals => { :apps => @apps} %>


<div class="box-content">
  <div class="row form-group">
    <div class="col-sm-2">包裝名稱</div>
    <div class="col-sm-2">APK類別</div>
    <div class="col-sm-2">測試結果</div>
    <div class="col-sm-2">複測結果</div>
    <div class="col-sm-2"></div>

  </div>
  <div class="row form-group">

    <%= form_tag search_querys_path, :method => :post,:multipart => true do %>
        <div class="col-sm-2">
          <%= select_tag "AppPackageName", options_for_select(@pkg,'') , { :class => 'form-control'}%>
        </div>
        <div class="col-sm-2">
          <%= select_tag "AppClass", options_for_select(@class,'',) ,{ :class => 'form-control'}%>
        </div>
        <div class="col-sm-2">
          <%= select_tag "ApkResult", options_for_select(@result,''), { :class => 'form-control'}%>
        </div>
        <div class="col-sm-2">
          <%= select_tag "TesterResult", options_for_select(@manual_result,''), { :class => 'form-control'}%>
        </div>
        <%= submit_tag 'Query', {:class => 'btn btn-primary'} %>

    <% end %>


  </div>
</div>

<div>
  <table class="table table-striped">
    <!-- Title -->
    <%= render :partial =>'form' %>

    <tbody>
    <% @apps.each do |app| %>
        <tr>
          <%= render :partial =>'apps', :locals => {:app=> app} %>

        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="btn-group col-md-1 col-md-offset-10" role="group" aria-label="...">

  <%= link_to "Download as CSV", {:controller => "testrun_apps", :action => "downloadcsv", "apps" => @apps ,:format => "csv"}%>


</div>

app/views/testrun_apps/show.html.erb
<%= link_to 'back index', testrun_apps_path %>
<div class="col-md-12">
  <table class="table table-striped">

    <thread>
      <tr>
        <th>#</th>
        <th>類別/分類</th>
        <th>名稱</th>
        <th>版本</th>
        <th>NDK</th>
        <th>總結果</th>
        <th>安裝測試</th>
        <th>啟動測試</th>
        <th>猴子測試</th>

        <th>複測</th>

      </tr>
    </thread>


    <tbody>
    <tr>
    <% app=@app%>
      <td><%= app.AppNumber %> <%= link_to image_tag("gp4.png"  , :width => 20 , :height => 20) , app.AppLink %></td>
      <td>
        <span class="label label-warning"><%= app.AppClass %></span>
        <span class="label label-info"> <%= app.AppCategory%></span>
      </td>
      <td>
        <div><%= app.AppName %></div>
        <div class="label label-success"><%= app.AppPackageName %></div>
      </td>
      <td><%= app.AppVersion %></td>
      <td><%= app.AppNativeCode %></td>
      <td><%= app.ApkResult %></td>
      <td><%= app.AppInstallResult%></td>
      <td><%= app.AppLaunchResult %></td>
      <td><%= app.AppMonkeyResult %></td>


        <td>
          <div class="pull-left">
            <dl class="dl-horizontal ">
              <dt class="pull-left">TTBugID</dt>
              <dd><%= app.TTBugID %></dd>
              <dt>BugZillaBugID</dt>
              <dd><%= app.BugZillaBugID %></dd>
              <dt>Tester</dt>
              <dd><%= app.Tester %></dd>
              <dt>TesterResult</dt>
              <dd><%= app.TesterResult %></dd>
              <dt>TesterComment</dt>
              <dd><%= app.TesterComment %></dd>

            </dl>

          </div>

        </td>



    </tr>
    </tbody>
  </table>
</div>