config/routes.rb
Rails.application.routes.draw do
  resources :testruns do
    resources :apps, :controller =>'testrun_apps' do
      collection do

      end

      end
  end

  resources :querys do
    collection do
      post :search
      post :downloadcsv
    end
  end

end

app/models/testrun.rb
class Testrun < ActiveRecord::Base
	has_many :apps
	
end

app/controllers/testruns_controller.rb
require 'json'
class TestrunsController < ApplicationController
	skip_before_action :verify_authenticity_token
	def index
		@testruns = Testrun.all
   # @app = App.find(1)


    respond_to do |format|
      format.html {}
      format.json { render :json => @testruns.to_json }
      format.xml { render :xml => @testruns.to_xml }

    end
	end

	def new
    file = File.read('report.json')
    data_hash = JSON.parse(file)

    tr = Testrun.new

    tr.TestRun_Time = data_hash["TestRun_Time"]
    tr.Product     = data_hash["Product"]
    tr.Project     = data_hash["Project"]
    tr.SerialNumber = data_hash["SerialNumber"]
    tr.DeviceVersion = data_hash["DeviceVersion"]
    tr.AndroidVersion = data_hash["AndroidVersion"]
    tr.SKU  = data_hash["SKU"]
    tr.ApkSKU = data_hash["APKSKU"]
    tr.TestRun_TotalAppsCount =data_hash["TestRun_TotalAppsCount"]
    tr.TestRun_TotalFailCount =data_hash["TestRun_TotalFailCount"]
    tr.TestRun_InstallFailCount =data_hash["TestRun_InstallFailCount"]
    tr.TestRun_LaunchRunningFail =data_hash["TestRun_LaunchRunningFail"]
    tr.TestRun_MonkeyRunningFail =data_hash["TestRun_MonkeyRunningFail"]
    tr.TestRun_PassRate  =data_hash["TestRun_PassRate"]
    data_hash["TestRun_Apps"].each_with_index { |app,index|
      ap = App.new
      ap.AppLink = app["AppLink"]
      ap.AppNumber = app["AppNumber"]
      ap.AppName = app["AppName"]
      ap.AppVersion =app["AppVersion"]
      ap.AppSKU = app["AppSKU"]
      ap.AppClass =app["AppClass"]
      ap.AppCategory =app["AppCategory"]
      ap.AppPackageName = app["AppPackageName"]
      ap.AppNativeCode = app["AppNativeCode"]
      ap.AppComment = app["AppComment"]
      ap.ApkStatus = app["ApkStatus"]
      ap.ApkResult = app["ApkResult"]
      ap.AppInstallResult = app["AppInstallResult"]
      ap.AppInstallFailReason = app["AppInstallReason"]
      ap.AppLaunchResult =app["AppLaunchResult"]
      ap.AppLaunchFailReason  =app["AppLaunchReason"]
      ap.AppMonkeyResult  =app["AppMonkeyResult"]
      ap.AppMonkeyFailReason  =app["AppMonkeyReason"]
      ap.testrun = tr
      ap.save

    }
    tr.save
    redirect_to testruns_url

	end





	def create
		#POST
		tr = Testrun.new

		tr.TestRun_Time = params[:TestRun_Time]
		tr.Product     = params[:Product]
    tr.Project     = params[:Project]
		tr.SerialNumber = params[:SerialNumber]
		tr.DeviceVersion = params[:DeviceVersion]
		tr.AndroidVersion = params[:AndroidVersion]
    tr.SKU  = params[:SKU]
    tr.ApkSKU = params[:APKSKU]
    tr.TestRun_TotalAppsCount =params[:TestRun_TotalAppsCount]
    tr.TestRun_TotalFailCount =params[:TestRun_TotalFailCount]
    tr.TestRun_InstallFailCount =params[:TestRun_InstallFailCount]
    tr.TestRun_LaunchRunningFail =params[:TestRun_LaunchRunningRail]
    tr.TestRun_MonkeyRunningFail =params[:TestRun_MonkeyRunningFail]
    tr.TestRun_PassRate  =params[:TestRun_PassRate]
    params[:TestRun_Apps].each_with_index {|app, index|
			ap = App.new
      ap.AppLink = app[:AppLink]
			ap.AppNumber = app[:AppNumber]
			ap.AppName = app[:AppName]
			ap.AppVersion =app[:AppVersion]
			ap.AppSKU = app[:AppSKU]
      ap.AppClass =app[:AppClass]
      ap.AppCategory =app[:AppCategory]
      ap.AppPackageName = app[:AppPackageName]
      ap.AppNativeCode = app[:AppNativeCode]
      ap.AppComment = app[:AppComment]
      ap.ApkStatus = app[:ApkStatus]
      ap.ApkResult = app[:ApkResult]
      ap.AppInstallResult = app[:AppInstallResult]
      ap.AppInstallFailReason = app[:AppInstallReason]
      ap.AppLaunchResult =app[:AppLaunchResult]
      ap.AppLaunchFailReason  =app[:AppLaunchReason]
      ap.AppMonkeyResult  = app[:AppMonkeyResult]
      ap.AppMonkeyFailReason = app[:AppMonkeyReason]
			ap.testrun = tr
			ap.save

		}
	    tr.save

		redirect_to testruns_url
	end



	def edit

	end


	def show
		redirect_to testruns_url
	end

	def destroy
		@testrun = Testrun.find(params[:id])

    @testrun.apps.destroy_all
    @testrun.destroy
		flash[:alert] = "event was successfully deleted"
		redirect_to testruns_url
	end

	def testrun_params
		params.require(:testrun).permit(:TestRun_Time)
	end

end

app/helpers/testruns_helper.rb
module TestrunsHelper
end

app/views/testruns/_form.html.erb
<thread>
  <tr>
    <th>測試時間</th>
    <th>專案</th>
    <th>序號</th>
    <th>SKU</th>
    <th>裝置版本</th>
    <th>Android版本</th>
    <th>總測試量</th>
    <th>總失敗數</th>
    <th>安裝失敗總數</th>
    <th>啟動失敗總數</th>
    <th>啟動測試結果</th>
    <th>猴子運行失敗總數</th>
    <th>成功率</th>

  </tr>
</thread>

app/views/testruns/index.html.erb
<div class="col-md-12">
	<label>
		<h2>Summary Report <span style="font-size: 16pt" class="badge"><%= @testruns.length %></span></h2>
	</label>
</div>


<div class="col-md-12">
	<table class="table table-striped">
		<thread>
			<tr>
				<th colspan="13">
					統計彙總
				</th>
			</tr>
		</thread>
           <%=  render :partial  => 'form' %>
		<tbody>


            <% @testruns.each do |testrun| %>
			<tr>

              <td><%= link_to testrun.TestRun_Time, testrun_apps_path(testrun) %></td>
				<td><%= testrun.Product%></td>
				<td><%= testrun.SerialNumber%></td>
                <td><%= testrun.SKU%></td>
				<td><%= testrun.DeviceVersion%></td>
				<td><%= testrun.AndroidVersion%></td>

              <td><%= testrun.TestRun_TotalAppsCount%></td>
              <td><%= testrun.TestRun_TotalFailCount%></td>
              <td><%= testrun.TestRun_InstallFailCount%></td>
              <td><%= testrun.TestRun_LaunchRunningFail%></td>
              <td><%= testrun.TestRun_MonkeyRunningFail%></td>
              <td><%= testrun.TestRun_PassRate%></td>
			 	<td><%= link_to 'Delete' , testrun_path(testrun), :method => :delete %></td>
			 </tr>
			<% end %>

			
		</tbody>
	</table>
</div>

app/views/testruns/new.html.erb
===
<%= debug(@ary_data) %>